language: java
sudo: false

jdk:
  - oraclejdk7

install: true
script: ./travis.sh
env:
  - TESTS=SONARQUBE_SNAPSHOT
  - TESTS=SONAR_CPP_SNAPSHOT

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
