language: java

jdk:
  - oraclejdk7
  - oraclejdk8

install: true
script: ./travis.sh
env:
  - TESTS=SONARQUBE_SNAPSHOT
  - TESTS=RUN_ITS_DEV
  - TESTS=RUN_ITS_LATEST

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
