language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - TESTS=SONARQUBE_SNAPSHOT
  - TESTS=SONAR_CPP_SNAPSHOT

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
